apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testask.urlConfig.defaultName" . }}
  labels:
    {{- include "testask.labels" . | nindent 4 }}
data:
  BACKEND_URL: "http://{{ include "testask.backend.service.name" . }}:{{ .Values.backend.service.port }}/"
